version: '2'
services:
    app:
        image: busybox
        volumes:
            - .:/var/www/app
        command: tail -f /dev/null

    nginx:
        image: nginx:1.11.6
        ports:
            - "80:80"
        working_dir: /var/www/app
        links:
            - php
        volumes_from:
            - app
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf

    php:
        image: evilfrog/starter-php:prod
        build: docker/images/php
        working_dir: /var/www/app
        links:
            - mysql
        volumes_from:
            - app
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/php.ini

    php-cli:
        image: evilfrog/starter-php-cli:prod
        build: docker/images/php
        working_dir: /var/www/app
        links:
            - mysql
        volumes_from:
            - app
        volumes:
            - ./etc/php/php-cli.ini:/usr/local/etc/php/php.ini

    mysql:
        image: mysql:5.7.16
        environment:
            MYSQL_ROOT_PASSWORD: ThisIsNotMentForAppsToKnowMakeItDifficultYeah
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project

    # cron:
    #     build: images/cron
    #     links:
    #         - mysql
    #     volumes_from:
    #         - app
